LobbyServer/Controllers/PlayLogController.cs
using ApiScheme.Scheme;
using LobbyServer.Models;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace LobbyServer.Controllers
{
    public class PlayLogController : BaseController
    {
        /// <summary>
        /// Shows PlayLogs.
        /// </summary>
        /// <param name="page"></param>
        /// <param name="partial"></param>
        /// <returns></returns>
        [OutputCache(Duration=10, VaryByParam="page,partial")]
        public ActionResult Index(int page = 0, bool partial = false)
        {
            return SingletonAction(() =>
            {
                var o = ApiScheme.Client.Api.Get<GetPlayLogsOut>(new GetPlayLogsIn() { page = page });
                if (partial)
                    return View("IndexPartial", o.playLogs);
                return View(new PlayLogIndexVM() { Page = page, PlayLogs = o.playLogs });
            }, page, partial);
        }

        /// <summary>
        /// Shows details of PlayLog.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [OutputCache(Duration=10, VaryByParam="id")]
        public ActionResult Details(int id = 0)
        {
            if (id == 0)
                return HttpNotFound();

            return SingletonAction(() =>
            {
                var o = ApiScheme.Client.Api.Get<GetPlayLogByIdOut>(new GetPlayLogByIdIn() { id = id });
                if (o.playLog == null)
                    return HttpNotFound();

                var url = ConfigurationManager.AppSettings["PlayLogUrl"] + o.playLog.fileName;
                var req = WebRequest.Create(url);
                string str;
                try
                {
                    using (var res = req.GetResponse())
                    {
                        using (var rs = res.GetResponseStream())
                        using (var reader = new StreamReader(rs, Encoding.UTF8))
                        {
                            str = reader.ReadToEnd();
                        }
                    }
                }
                catch
                {
                    return HttpNotFound();
                }

                return Content(str);
            }, id);
        }

        /// <summary>
        /// Lets User download a PlayLog.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [OutputCache(Duration=10, VaryByParam="id")]
        public ActionResult Download(int id = 0)
        {
            if (id == 0)
                return HttpNotFound();

            return SingletonAction(() =>
            {
                var o = ApiScheme.Client.Api.Get<GetPlayLogByIdOut>(new GetPlayLogByIdIn() { id = id });
                if (o.playLog == null)
                    return HttpNotFound();

                var url = ConfigurationManager.AppSettings["PlayLogUrl"] + o.playLog.fileName;
                var req = WebRequest.Create(url);
                string str;
                try
                {
                    using (var res = req.GetResponse())
                    {
                        using (var rs = res.GetResponseStream())
                        using (var reader = new StreamReader(rs, Encoding.UTF8))
                        {
                            str = reader.ReadToEnd();
                        }
                    }
                }
                catch
                {
                    return HttpNotFound();
                }

                return File(Encoding.UTF8.GetBytes(str), "application/octet-stream", o.playLog.fileName);
            }, id);
        }

	}
}

LobbyServer/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LobbyServer.Controllers
{
    public class UserController : PassAuthenticatedController
    {
        public ActionResult ExternalLogin(string entryPassString = null, string finalDestination = null)
        {
            TryLogin(entryPassString);

            Debug.WriteLine("EntryPassString: " + entryPassString);
            Debug.WriteLine("FinalDestination: " + finalDestination);

            var uri = new Uri(finalDestination);
            if (uri.Authority != Request.Url.Authority)
                throw new Exception(string.Format("Authority not match. finalDestination: {0} RequestUrl: {1}", finalDestination, Request.Url.AbsoluteUri));
            return Redirect(uri.LocalPath);
        }

        public ActionResult Logout()
        {
            ClearPass();
            //return Redirect("http://accounts.google.com/Logout");
            return View();
            //return RedirectToAction("Index", "Home");
        }
	}
}

LobbyServer/Views/Shared/_AdPartial.cshtml
@model LobbyServer.Models.AdPartialVM

@if (Model.Key == "Head")
{
    <script type='text/javascript'>
        var googletag = googletag || {};
        googletag.cmd = googletag.cmd || [];
        (function () {
            var gads = document.createElement('script');
            gads.async = true;
            gads.type = 'text/javascript';
            var useSSL = 'https:' == document.location.protocol;
            gads.src = (useSSL ? 'https:' : 'http:') +
            '//www.googletagservices.com/tag/js/gpt.js';
            var node = document.getElementsByTagName('script')[0];
            node.parentNode.insertBefore(gads, node);
        })();
    </script>
    <script type='text/javascript'>
        googletag.cmd.push(function () {
            googletag.defineSlot('/91519777/JGO-Root-Top-PC', [728, 90], 'div-gpt-ad-1382526207957-0').addService(googletag.pubads());
            googletag.defineSlot('/91519777/JGO-Root-MLeft-PC', [300, 250], 'div-gpt-ad-1382588561003-0').addService(googletag.pubads());
            googletag.defineSlot('/91519777/JGO-Root-MRight-PC', [300, 250], 'div-gpt-ad-1382590896721-0').addService(googletag.pubads());
            googletag.defineSlot('/91519777/JGO-Root-Top-Mobile', [320, 50], 'div-gpt-ad-1382595991674-0').addService(googletag.pubads());
            googletag.defineSlot('/91519777/JGO-Root-Middle-Mobile', [320, 50], 'div-gpt-ad-1382603425559-0').addService(googletag.pubads());
            googletag.defineSlot('/91519777/JGO-Root-Bottom-Mobile', [300, 250], 'div-gpt-ad-1382603476746-0').addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
        });
    </script>
    return;
}

@if (!UserAgent.IsMobile())
{
    switch (Model.Key)
    {
        case "Root-Top":
            <!-- JGO-Root-Top-PC -->
            <div id='div-gpt-ad-1382526207957-0' style='width:728px; height:90px; padding: 0; margin: 0 0 10px 0;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function () { googletag.display('div-gpt-ad-1382526207957-0'); });
                </script>
            </div>
            break;

        case "Root-Middle":
            break;

        case "Root-Bottom":
        <table style="margin-bottom: 10px;">
            <tr>
                <td>
                    <!-- JGO-Root-MLeft-PC -->
                    <div id='div-gpt-ad-1382588561003-0' style='width: 300px; height: 250px; padding: 0; margin-right: 10px;'>
                        <script type='text/javascript'>
                            googletag.cmd.push(function () { googletag.display('div-gpt-ad-1382588561003-0'); });
                        </script>
                    </div>
                </td>
                <td>
                    <!-- JGO-Root-MRight-PC -->
                    <div id='div-gpt-ad-1382590896721-0' style='width:300px; height:250px; padding: 0;'>
                        <script type='text/javascript'>
                            googletag.cmd.push(function () { googletag.display('div-gpt-ad-1382590896721-0'); });
                        </script>
                    </div>
                </td>
            </tr>
        </table>
            break;
    }
}
else
{
    switch (Model.Key)
    {
        case "Root-Top":
            <div class="row">
                <!-- JGO-Root-Top-Mobile -->
                <div id='div-gpt-ad-1382595991674-0' style='width:320px; height:50px; padding: 0; margin-bottom: 10px;'>
                    <script type='text/javascript'>
                        googletag.cmd.push(function () { googletag.display('div-gpt-ad-1382595991674-0'); });
                    </script>
                </div>
            </div>
            break;

        case "Root-Middle":
            <!-- JGO-Root-Middle-Mobile -->
        <div id='div-gpt-ad-1382603425559-0' style='width: 320px; height: 50px; padding-bottom: 10px;'>
            <script type='text/javascript'>
                googletag.cmd.push(function () { googletag.display('div-gpt-ad-1382603425559-0'); });
            </script>
        </div>
            break;

        case "Root-Bottom":
            <!-- JGO-Root-Bottom-Mobile -->
        <div id='div-gpt-ad-1382603476746-0' style='width: 300px; height: 250px; padding: 0; margin-bottom: 10px;'>
            <script type='text/javascript'>
                googletag.cmd.push(function () { googletag.display('div-gpt-ad-1382603476746-0'); });
            </script>
        </div>
            break;
    }
}

LobbyServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0" />
    @{
        var title = _.ApplicationName;
        if(ViewBag.Title != null){
            title = ViewBag.Title + " - " + title;
        }
    }
    <title>@title</title>
    @if (ViewBag.CanonicalUrl != null)
    {
        <link rel="canonical" href="@ViewBag.CanonicalUrl" />
    }
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Html.Partial("_AdPartial", new LobbyServer.Models.AdPartialVM() { Key = "Head" })

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(_.ApplicationName, "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Game")"><span class="glyphicon glyphicon-play"></span> 参加する</a></li>
                    <li><a href="@Url.Action("Index", "PlayLog")"><span class="glyphicon glyphicon-book"></span> 村の記録</a></li>
                    <li><a href="@Url.Action("About", "Home")"><span class="glyphicon glyphicon-question-sign"></span> 遊び方</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Logout", "User")">ログアウト</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial("_AdPartial", new LobbyServer.Models.AdPartialVM() { Key = "Root-Top" })
        @RenderBody()
        @Html.Partial("_AdPartial", new LobbyServer.Models.AdPartialVM() { Key = "Root-Bottom" })
        <div class="box">
            <footer>&copy; @DateTime.Now.Year - @_.ApplicationName</footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>